### ISSUE TITLE
jq issue 

### ISSUE THREAD

**Issue by sebastienbrun38** [open-toolchain/toolchain-to-template#3]
I solve an issue (--inplace feature not available) on catalina 15.02 with jq by upgrade from 1.6 to 2.4.1

Perhaps add a step to verify version of jq before starting the template generation.

Regards.

**Comment by jauninb** [comment]
@sebastienbrun38 i am assuming this is `yq` tool you are refering to. An update in the README.md will be done to retstate the expected minimal version of required tooling.

**Comment by jauninb** [comment]
Update made in the README.md
