### ISSUE TITLE
Infinite Loop Caused by Missing Empty String Check

### ISSUE THREAD

**Issue by L3XANDR0** [open-toolchain/toolchain-to-template#6]
I used this project to export a toolchain, but I couldn't at first until I added empty string checks to the if-statements containing breaks. 

OS: Catalina 10.15.3
IBM Cloud CLI: 0.22.0-5ccbbea-2020-01-21T09:49:02+00:00
yq: 3.1.0
jq: 1.6
Pipeline: Classic

**Comment by jauninb** [comment]
This seems related to th yq version - there is some change between v2 and v3 that breaks the logic - for instance https://mikefarah.gitbook.io/yq/upgrading-from-v2#reading-paths-that-dont-exist

**Comment by sebastienbrun38** [comment]
Hello Benoit,

We are running with jq 1.6 and yq 2.4.0 and we have this issue  running on ubuntu

yq: error: argument files: can't open 'services[0].service_id': [Errno 2] No such file or directory: 'services[0].service_id'
Found 0:

It's issue appear multiple times 

Do you think it's also possible to add a DockerFile to have a ready to run solution

**Comment by maire-kehoe** [comment]
Note, the initial problem described here by @L3XANDR0 above should now be fixed, as this PR change has been merged to master:
- support for yq 3
  https://github.com/open-toolchain/toolchain-to-template/pull/7

**Comment by maire-kehoe** [comment]
@sebastienbrun38 The lines of code relevant to the error you're seeing are:
https://github.com/open-toolchain/toolchain-to-template/blob/master/toolchain-to-template.sh#L291
> OLD_TOOLCHAIN_JSON_FILE="tmp.old_toolchain.json"

https://github.com/open-toolchain/toolchain-to-template/blob/master/toolchain-to-template.sh#L315
>  SERVICE_ID=$(yq read "${OLD_TOOLCHAIN_JSON_FILE}" "services[${i}].service_id")


So if you're seeing:
> yq: error: argument files: can't open 'services[0].service_id': [Errno 2] No such file or directory: 'services[0].service_id'

then its behaving as if the OLD_TOOLCHAIN_JSON_FILE variable was set to "" (empty string), 
but that variable isn't set again after it's initialized, so it should have the value that was set at that first line. 
Not sure what's happening there. 
Maybe the variable assignment isn't working with your operating system / permissions, or I guess maybe if your version of bash is old enough maybe the "${something}" variable brace expansion syntax isn't supported (just $something is an older syntax). Not sure.

**Comment by jauninb** [comment]
closing issue as the loop related to up-to-date version of `yq` has been solved
